"""add scan_tasks table

Revision ID: a010398ea2cc
Revises: 
Create Date: 2025-09-03 17:21:27.074418

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a010398ea2cc'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scan_tasks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('scan_task_id', sa.String(length=64), nullable=False, comment='任务唯一标识'),
    sa.Column('task_name', sa.String(length=255), nullable=True, comment='任务名称'),
    sa.Column('task_status', sa.Integer(), server_default=sa.text('0'), nullable=False, comment='任务状态：0-待执行 1-执行中 2-成功 3-失败'),
    sa.Column('is_enabled', sa.Integer(), server_default=sa.text('1'), nullable=False, comment='启用状态：0-禁用 1-启用'),
    sa.Column('scan_dir', sa.String(length=255), nullable=True, comment='扫描目录'),
    sa.Column('scan_mode', sa.Integer(), nullable=True, comment='扫描模式：0-全量+增量 1-增量 2-全量'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scan_tasks_scan_task_id'), 'scan_tasks', ['scan_task_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scan_tasks_scan_task_id'), table_name='scan_tasks')
    op.drop_table('scan_tasks')
    # ### end Alembic commands ###
